CREATE TABLE 'GP1' ('DATE_TIME' TEXT,'PLANT_ID' INTEGER,'SOURCE_KEY' TEXT,'DC_POWER' REAL,'AC_POWER' REAL,'DAILY_YIELD' REAL,'TOTAL_YIELD' REAL);
CREATE TABLE 'CP1' ('DATE_TIME' TEXT,'PLANT_ID' INTEGER,'SOURCE_KEY' TEXT,'AMBIENT_TEMPERATURE' REAL,'MODULE_TEMPERATURE' REAL,'IRRADIATION' REAL);
CREATE TABLE 'GP2' ('DATE_TIME' TEXT,'PLANT_ID' INTEGER,'SOURCE_KEY' TEXT,'DC_POWER' REAL,'AC_POWER' REAL,'DAILY_YIELD' REAL,'TOTAL_YIELD' REAL);
CREATE TABLE 'CP2' ('DATE_TIME' TEXT,'PLANT_ID' INTEGER,'SOURCE_KEY' TEXT,'AMBIENT_TEMPERATURE' REAL,'MODULE_TEMPERATURE' REAL,'IRRADIATION' REAL);